vich_uploader:
    db_driver: orm

    mappings:
        oeuvre_image:
            uri_prefix: /img/oeuvres
            upload_destination: '%kernel.project_dir%/public/img/oeuvres'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

